import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {SocketProvider} from '../utils/context'
import './globals.css'
import { Socket } from 'socket.io-client'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SocketProvider socketId=''>
      <html lang="en">
        <body className={inter.className}>
            {children}
        </body>
      </html>
    </SocketProvider>
  )
}
